# Generated by Django 2.1.3 on 2018-12-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='feeling',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='music',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
