# Generated by Django 2.1.3 on 2018-12-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_story', '0002_auto_20181218_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='solution',
            field=models.TextField(blank=True),
        ),
    ]
